### ISSUE TITLE
New install

### ISSUE THREAD

**Issue by Smith-Chris1** [luxbe/klwe#1]
Love the idea of this. Just downloaded it and ran it, I'm getting this error on my localhost webpage:

`Error: Unrecognized option 'enableSourcemap'
    at file:///Users/ME/Desktop/SupportingFiles/scripts/klwe/klwe/node_modules/svelte/compiler.mjs:31270:19
    at Array.forEach (<anonymous>)
    at validate_options (file:///Users/ME/Desktop/SupportingFiles/scripts/klwe/klwe/node_modules/svelte/compiler.mjs:31264:26)
    at compile (file:///Users/ME/Desktop/SupportingFiles/scripts/klwe/klwe/node_modules/svelte/compiler.mjs:31308:5)
    at compileSvelte2 (file:///Users/ME/Desktop/SupportingFiles/scripts/klwe/klwe/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:313:20)
    at async TransformContext.transform (file:///Users/ME/Desktop/SupportingFiles/scripts/klwe/klwe/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:1460:27)
    at async Object.transform (/Users/ME/Desktop/SupportingFiles/scripts/klwe/klwe/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:42396:30)
    at async doTransform (/Users/ME/Desktop/SupportingFiles/scripts/klwe/klwe/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:56797:29)`

**Comment by Smith-Chris1** [comment]
found the answer, install the newest version of svelte-kit:

npm i @sveltejs/kit

**Comment by luxbe** [comment]
I don't think I can do anything about that - the only version I can put in the package.json is `next`. Let me know, if I can change anything to prevent this from happening in the future :)
Otherwise I will close this issue now
